import turtle
window = turtle.Screen()
batz = turtle.Turtle()
batz.shape("turtle")
batz.speed(8)
batz.penup()
batz.goto(0,0)

batz.fillcolor("yellow")
batz.begin_fill()
batz.pendown()
batz.circle(50)
batz.end_fill()

batz.penup()
batz.goto(-20, 40)
batz.setheading(270)
batz.pendown()
batz.circle(20, 180)
batz.penup()

batz.goto(-15, 60)
batz.pendown()
batz.fillcolor("black")
batz.begin_fill()
batz.circle(5)
batz.end_fill()
batz.penup()

batz.goto(20, 60)
batz.pendown()
batz.fillcolor("black")
batz.begin_fill()
batz.circle(5)
batz.end_fill()
batz.penup()
batz.goto(480, 480)